# Generated by Django 5.2.6 on 2025-09-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, help_text='The city derived from the IP address.', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, help_text='The country derived from the IP address.', max_length=100, null=True, verbose_name='Country'),
        ),
    ]
