# Generated by Django 5.2.6 on 2025-09-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='An IP address flagged for suspicious activity.', unique=True, verbose_name='Suspicious IP Address')),
                ('reason', models.TextField(help_text='Reason(s) why this IP was flagged as suspicious.', verbose_name='Reason')),
                ('flagged_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the IP was flagged.', verbose_name='Flagged At')),
                ('is_resolved', models.BooleanField(default=False, help_text='Indicates if the suspicious activity has been investigated and resolved.', verbose_name='Is Resolved')),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-flagged_at'],
            },
        ),
    ]
